"""Added cascade delete all for wallet entries of service_users that are deleted

Revision ID: 10a3e2ac1ac3
Revises: 8737d3a4dd11
Create Date: 2024-08-14 16:15:28.718284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a3e2ac1ac3'
down_revision = '8737d3a4dd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.drop_constraint('wallet_entry_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wallet_entry_staff_id_fkey', 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###
