"""Added is_cash_removed field to WalletEntry table. to store cash being out for all users and not just in the session

Revision ID: 1d3135eef2ec
Revises: 10a3e2ac1ac3
Create Date: 2024-08-15 16:26:04.086052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3135eef2ec'
down_revision = '10a3e2ac1ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cash_removed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.drop_column('is_cash_removed')

    # ### end Alembic commands ###
