"""added fields bank_out bank_in and reciept_number to better represent a FRS sheet

Revision ID: b1985c265474
Revises: af0196fa1984
Create Date: 2024-08-09 11:33:05.191539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1985c265474'
down_revision = 'af0196fa1984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_out', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bank_in', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('bank_in')
        batch_op.drop_column('bank_out')

    # ### end Alembic commands ###
