"""Change Float to Numeric for financial fields

Revision ID: c542f7a0681c
Revises: b1985c265474
Create Date: 2024-08-10 13:07:25.348497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c542f7a0681c'
down_revision = 'b1985c265474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.alter_column('cash_amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('bank_amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cash_out',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cash_in',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('money_spent',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bank_out',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('bank_in',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_entry', schema=None) as batch_op:
        batch_op.alter_column('bank_in',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bank_out',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('money_spent',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cash_in',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cash_out',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bank_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('cash_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
